name: DevSecOps Pipeline
on:
  push:
    branches:
      - main
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
  
jobs:
  build-scan-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: |
         docker build -t my-app:latest ./app
      - name: Install Trivy
        run: |
          sudo apt-get update && sudo apt-get install -y curl
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb
      - name: Scan Docker Image with Trivy
        run: |
          trivy image --exit-code 0 devops-app:latest
      - name: Deploy step (simulation)
        run: |
                echo "deploying to kubernetes"
    
